import { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import { Box } from "@mui/material";
import Footer from "@/Components/Footer";
import Navbar from "@/Components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Box pb={10}>
            <Navbar />
            {children}
            <Footer />
          </Box>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
